[package]
name = "todo_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.16", features = ["derive"] }
#console_engine = "2.6.1"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
